#! /bin/bash

pid=$(lsof -ti :8082)

if [ -z "$pid" ]; then
  echo "사용중인 프로세스 X"
else
  # PID를 이용하여 프로세스 종료
  kill -9 "$pid"
  echo "포트 8082를 사용중인 프로세스 종료"
fi

pid=$(lsof -ti :8081)

if [ -z "$pid" ]; then
  echo "사용중인 프로세스 X"
else
  # PID를 이용하여 프로세스 종료
  kill -9 "$pid"
  echo "포트 8081를 사용중인 프로세스 종료"
fi

pid=$(lsof -ti :8083)

if [ -z "$pid" ]; then
  echo "사용중인 프로세스 X"
else
  # PID를 이용하여 프로세스 종료
  kill -9 "$pid"
  echo "포트 8083를 사용중인 프로세스 종료"
fi

cd /Users/sinseung-yong/Desktop/recycle-test/be

./gradlew :review:bootRun --args='--spring.profiles.active=local' &
./gradlew :member:bootRun --args='--spring.profiles.active=local' &
./gradlew :notification:bootRun --args='--spring.profiles.active=local' &